"""CIDC25 datasets: self-supervised windows with Anscombe + gain augmentation.

The three training signals are all generated by a single
``CIDCStackDataset`` that yields *raw ADU windows*. Per-model wrappers
then transform those windows into the ``(input, target)`` pair expected
by each architecture:

- :class:`DeepInterpDataset` — drop center frame ``(2K, H, W) → (1, H, W)``.
- :class:`N2V3DDataset`      — sparse blind-spot mask on ``(1, T, H, W)``.
- :class:`DeepCADDataset`    — split odd/even halves of ``(1, 2T, H, W)``.

Gain augmentation is applied at the window level in raw ADU, then the
result is Anscombe-transformed before being returned to the model.
"""

from .dataset import (
    CIDCStackDataset,
    DeepCADDataset,
    DeepInterpDataset,
    N2V3DDataset,
    build_dataset,
)

__all__ = [
    "CIDCStackDataset",
    "DeepInterpDataset",
    "N2V3DDataset",
    "DeepCADDataset",
    "build_dataset",
]
